plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.vpnblocker'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.vpnblocker"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
